<?php

namespace ContainerPGTLqw4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lbpz6rGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lbpz6rG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lbpz6rG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loan' => ['privates', '.errored..service_locator.Lbpz6rG.App\\Entity\\Loan', NULL, 'Cannot autowire service ".service_locator.Lbpz6rG": it needs an instance of "App\\Entity\\Loan" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'loan' => 'App\\Entity\\Loan',
            'entityManager' => '?',
        ]);
    }
}
