<?php

namespace ContainerPGTLqw4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8PowHhTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8PowHhT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8PowHhT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuthorController::index' => ['privates', '.service_locator..WkD5qS.App\\Controller\\AuthorController::index()', 'getAuthorControllerindexService', true],
            'App\\Controller\\AuthorController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AuthorController::new()', 'getAuthorControllernewService', true],
            'App\\Controller\\AuthorController::show' => ['privates', '.service_locator.s29OJQA.App\\Controller\\AuthorController::show()', 'getAuthorControllershowService', true],
            'App\\Controller\\AuthorController::edit' => ['privates', '.service_locator.Oi6VS8j.App\\Controller\\AuthorController::edit()', 'getAuthorControllereditService', true],
            'App\\Controller\\AuthorController::delete' => ['privates', '.service_locator.Oi6VS8j.App\\Controller\\AuthorController::delete()', 'getAuthorControllerdeleteService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BookController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\BookController::show' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\BookController::show()', 'getBookControllershowService', true],
            'App\\Controller\\BookController::edit' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::edit()', 'getBookControllereditService', true],
            'App\\Controller\\BookController::delete' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::delete()', 'getBookControllerdeleteService', true],
            'App\\Controller\\LoanController::index' => ['privates', '.service_locator.EChwSvL.App\\Controller\\LoanController::index()', 'getLoanControllerindexService', true],
            'App\\Controller\\LoanController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\LoanController::new()', 'getLoanControllernewService', true],
            'App\\Controller\\LoanController::show' => ['privates', '.service_locator.XR5qMF1.App\\Controller\\LoanController::show()', 'getLoanControllershowService', true],
            'App\\Controller\\LoanController::edit' => ['privates', '.service_locator.Lbpz6rG.App\\Controller\\LoanController::edit()', 'getLoanControllereditService', true],
            'App\\Controller\\LoanController::delete' => ['privates', '.service_locator.Lbpz6rG.App\\Controller\\LoanController::delete()', 'getLoanControllerdeleteService', true],
            'App\\Controller\\ReaderController::index' => ['privates', '.service_locator.FrnPksi.App\\Controller\\ReaderController::index()', 'getReaderControllerindexService', true],
            'App\\Controller\\ReaderController::new' => ['privates', '.service_locator.A84gqGd.App\\Controller\\ReaderController::new()', 'getReaderControllernewService', true],
            'App\\Controller\\ReaderController::show' => ['privates', '.service_locator.itq0.oo.App\\Controller\\ReaderController::show()', 'getReaderControllershowService', true],
            'App\\Controller\\ReaderController::edit' => ['privates', '.service_locator.UFADWkW.App\\Controller\\ReaderController::edit()', 'getReaderControllereditService', true],
            'App\\Controller\\ReaderController::delete' => ['privates', '.service_locator.0_rr8BZ.App\\Controller\\ReaderController::delete()', 'getReaderControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuthorController:index' => ['privates', '.service_locator..WkD5qS.App\\Controller\\AuthorController::index()', 'getAuthorControllerindexService', true],
            'App\\Controller\\AuthorController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AuthorController::new()', 'getAuthorControllernewService', true],
            'App\\Controller\\AuthorController:show' => ['privates', '.service_locator.s29OJQA.App\\Controller\\AuthorController::show()', 'getAuthorControllershowService', true],
            'App\\Controller\\AuthorController:edit' => ['privates', '.service_locator.Oi6VS8j.App\\Controller\\AuthorController::edit()', 'getAuthorControllereditService', true],
            'App\\Controller\\AuthorController:delete' => ['privates', '.service_locator.Oi6VS8j.App\\Controller\\AuthorController::delete()', 'getAuthorControllerdeleteService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BookController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\BookController:show' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\BookController::show()', 'getBookControllershowService', true],
            'App\\Controller\\BookController:edit' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::edit()', 'getBookControllereditService', true],
            'App\\Controller\\BookController:delete' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::delete()', 'getBookControllerdeleteService', true],
            'App\\Controller\\LoanController:index' => ['privates', '.service_locator.EChwSvL.App\\Controller\\LoanController::index()', 'getLoanControllerindexService', true],
            'App\\Controller\\LoanController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\LoanController::new()', 'getLoanControllernewService', true],
            'App\\Controller\\LoanController:show' => ['privates', '.service_locator.XR5qMF1.App\\Controller\\LoanController::show()', 'getLoanControllershowService', true],
            'App\\Controller\\LoanController:edit' => ['privates', '.service_locator.Lbpz6rG.App\\Controller\\LoanController::edit()', 'getLoanControllereditService', true],
            'App\\Controller\\LoanController:delete' => ['privates', '.service_locator.Lbpz6rG.App\\Controller\\LoanController::delete()', 'getLoanControllerdeleteService', true],
            'App\\Controller\\ReaderController:index' => ['privates', '.service_locator.FrnPksi.App\\Controller\\ReaderController::index()', 'getReaderControllerindexService', true],
            'App\\Controller\\ReaderController:new' => ['privates', '.service_locator.A84gqGd.App\\Controller\\ReaderController::new()', 'getReaderControllernewService', true],
            'App\\Controller\\ReaderController:show' => ['privates', '.service_locator.itq0.oo.App\\Controller\\ReaderController::show()', 'getReaderControllershowService', true],
            'App\\Controller\\ReaderController:edit' => ['privates', '.service_locator.UFADWkW.App\\Controller\\ReaderController::edit()', 'getReaderControllereditService', true],
            'App\\Controller\\ReaderController:delete' => ['privates', '.service_locator.0_rr8BZ.App\\Controller\\ReaderController::delete()', 'getReaderControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AuthorController::index' => '?',
            'App\\Controller\\AuthorController::new' => '?',
            'App\\Controller\\AuthorController::show' => '?',
            'App\\Controller\\AuthorController::edit' => '?',
            'App\\Controller\\AuthorController::delete' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\BookController::new' => '?',
            'App\\Controller\\BookController::show' => '?',
            'App\\Controller\\BookController::edit' => '?',
            'App\\Controller\\BookController::delete' => '?',
            'App\\Controller\\LoanController::index' => '?',
            'App\\Controller\\LoanController::new' => '?',
            'App\\Controller\\LoanController::show' => '?',
            'App\\Controller\\LoanController::edit' => '?',
            'App\\Controller\\LoanController::delete' => '?',
            'App\\Controller\\ReaderController::index' => '?',
            'App\\Controller\\ReaderController::new' => '?',
            'App\\Controller\\ReaderController::show' => '?',
            'App\\Controller\\ReaderController::edit' => '?',
            'App\\Controller\\ReaderController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AuthorController:index' => '?',
            'App\\Controller\\AuthorController:new' => '?',
            'App\\Controller\\AuthorController:show' => '?',
            'App\\Controller\\AuthorController:edit' => '?',
            'App\\Controller\\AuthorController:delete' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\BookController:new' => '?',
            'App\\Controller\\BookController:show' => '?',
            'App\\Controller\\BookController:edit' => '?',
            'App\\Controller\\BookController:delete' => '?',
            'App\\Controller\\LoanController:index' => '?',
            'App\\Controller\\LoanController:new' => '?',
            'App\\Controller\\LoanController:show' => '?',
            'App\\Controller\\LoanController:edit' => '?',
            'App\\Controller\\LoanController:delete' => '?',
            'App\\Controller\\ReaderController:index' => '?',
            'App\\Controller\\ReaderController:new' => '?',
            'App\\Controller\\ReaderController:show' => '?',
            'App\\Controller\\ReaderController:edit' => '?',
            'App\\Controller\\ReaderController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
