<?php

namespace ContainerPGTLqw4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoanControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lbpz6rG.App\Controller\LoanController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lbpz6rG.App\\Controller\\LoanController::delete()'] = ($container->privates['.service_locator.Lbpz6rG'] ?? $container->load('get_ServiceLocator_Lbpz6rGService'))->withContext('App\\Controller\\LoanController::delete()', $container);
    }
}
