<?php

namespace ContainerPGTLqw4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReaderControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.itq0.oo.App\Controller\ReaderController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.itq0.oo.App\\Controller\\ReaderController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reader' => ['privates', '.errored..service_locator.itq0.oo.App\\Entity\\Reader', NULL, 'Cannot autowire service ".service_locator.itq0.oo": it needs an instance of "App\\Entity\\Reader" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'reader' => 'App\\Entity\\Reader',
        ]))->withContext('App\\Controller\\ReaderController::show()', $container);
    }
}
