<?php

namespace ContainerPGTLqw4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReader3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.itq0.oo.App\Entity\Reader' shared service.
     *
     * @return \App\Entity\Reader
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.itq0.oo": it needs an instance of "App\\Entity\\Reader" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
