<?php

namespace Container3I3YVJ6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TBu.yVo.App\Controller\HomeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TBu.yVo.App\\Controller\\HomeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
            'readerRepository' => ['privates', 'App\\Repository\\ReaderRepository', 'getReaderRepositoryService', true],
            'loanRepository' => ['privates', 'App\\Repository\\LoanRepository', 'getLoanRepositoryService', true],
            'authorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
        ], [
            'bookRepository' => 'App\\Repository\\BookRepository',
            'readerRepository' => 'App\\Repository\\ReaderRepository',
            'loanRepository' => 'App\\Repository\\LoanRepository',
            'authorRepository' => 'App\\Repository\\AuthorRepository',
        ]))->withContext('App\\Controller\\HomeController::index()', $container);
    }
}
