<?php

namespace Container3I3YVJ6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoanControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EChwSvL.App\Controller\LoanController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EChwSvL.App\\Controller\\LoanController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loanRepository' => ['privates', 'App\\Repository\\LoanRepository', 'getLoanRepositoryService', true],
        ], [
            'loanRepository' => 'App\\Repository\\LoanRepository',
        ]))->withContext('App\\Controller\\LoanController::index()', $container);
    }
}
