<?php

namespace Container3I3YVJ6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoanControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XR5qMF1.App\Controller\LoanController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XR5qMF1.App\\Controller\\LoanController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loan' => ['privates', '.errored..service_locator.XR5qMF1.App\\Entity\\Loan', NULL, 'Cannot autowire service ".service_locator.XR5qMF1": it needs an instance of "App\\Entity\\Loan" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'loan' => 'App\\Entity\\Loan',
        ]))->withContext('App\\Controller\\LoanController::show()', $container);
    }
}
