<?php

namespace Container3I3YVJ6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoanService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Lbpz6rG.App\Entity\Loan' shared service.
     *
     * @return \App\Entity\Loan
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Lbpz6rG": it needs an instance of "App\\Entity\\Loan" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
