<?php

namespace Container3I3YVJ6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReaderControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FrnPksi.App\Controller\ReaderController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FrnPksi.App\\Controller\\ReaderController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'readerRepository' => ['privates', 'App\\Repository\\ReaderRepository', 'getReaderRepositoryService', true],
        ], [
            'readerRepository' => 'App\\Repository\\ReaderRepository',
        ]))->withContext('App\\Controller\\ReaderController::index()', $container);
    }
}
