<?php

namespace Container3I3YVJ6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReaderControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0_rr8BZ.App\Controller\ReaderController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0_rr8BZ.App\\Controller\\ReaderController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reader' => ['privates', '.errored..service_locator.0_rr8BZ.App\\Entity\\Reader', NULL, 'Cannot autowire service ".service_locator.0_rr8BZ": it needs an instance of "App\\Entity\\Reader" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'reader' => 'App\\Entity\\Reader',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ReaderController::delete()', $container);
    }
}
