<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPGTLqw4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPGTLqw4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPGTLqw4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPGTLqw4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPGTLqw4\App_KernelDevDebugContainer([
    'container.build_hash' => 'PGTLqw4',
    'container.build_id' => '6bf2b8b6',
    'container.build_time' => 1765750241,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPGTLqw4');
